### ISSUE TITLE
testcase papi_ld_ins hang indefinitely on Neoverse N1

### ISSUE THREAD

**Issue by aaronmerey** [icl-utk-edu/papi#456]
After updating to commit 7710a20ed72b the validation tests papi_ld_ins hang indefinitely when run on an ARM Neoverse N1 system.

This occurs in the execute_loads and execute_stores assembly routines introduced by that commit.  It appears that an infinite loop is caused by the loop counters that are part of the test not progressing as expected on Neoverse N1.

System:
    Architecture: ARMv8 (AArch64)
    Microarchitecture: Neoverse N1
    OS: Fedora rawhide (Linux 6.16.0-0.rc5.16.fc43.aarch64)

**Comment by Treece-Burgess** [comment]
Hello @aaronmerey, I will need to see if I can get access to an ARM Neoverse N1; however, on an ARM Neoverse V2 I cannot trigger an infinite loop with the `papi_ld_ins` validation test:
```
Testing PAPI_LD_INS

Testing a sleep of 1 second (3 times):
	Average should be low, as no loads when sleeping
	Measured average: 285

Testing a large number of loads
Estimated loads: 268697600
	Actual measured loads = 268698324
	Expected 268697600, got 268698324
	Error=0.00%

Testing for a linear cycle increase
	Expected 537396648, got 537396327
	Error=-0.00%

PASSED
```

Beside the current provided information, could you provide your PAPI configure and any extra compiler flags you may have used?

**Comment by dbarry9** [comment]
I am unable to reproduce this issue on a system with the following:
- ARM Neoverse-N1 architecture
- GCC 11.5.0
- PAPI master branch

Here are the steps I used to build PAPI:
- ./configure --prefix=${PWD}/installation --with-components=""
- make -j8
- make install

I ran the following, which completed in about 5 minutes.
```
for i in {1..100}
do
    ./validation_tests/papi_ld_ins
done
```

Here is the output from one of my invocations of the `papi_ld_ins` test:
>Testing PAPI_LD_INS
>
>Testing a sleep of 1 second (3 times):
>        Average should be low, as no loads when sleeping
>        Measured average: 238
>
>Testing a large number of loads
>Estimated loads: 268697600
>        Actual measured loads = 268698581
>        Expected 268697600, got 268698581
>        Error=0.00%
>
>Testing for a linear cycle increase
>        Expected 537397162, got 537397165
>        Error=0.00%
>
>PASSED

Do you still encounter this issue? Do you recall the compiler version and configure command that you used?

**Comment by dbarry9** [comment]
I still have not been able to recreate this issue; however, I realized that there is a bug in the logic for the `papi_ld_ins` and `papi_sr_ins` validation tests, which I have addressed in PR #671.

If you have the change, could you please checkout this PR and let me know if it resolves the issue on your end?

**Comment by aaronmerey** [comment]
Hi @dbarry9. I checked out #671 and it doesn't fix this.

I believe the issue is caused by the assembly instructions in src/validation_tests/load_store_testcode.c. ldvar/stvar are 4-byte .words accessed with 8-byte ldr/str, so both overrun by 4 bytes.

The hang comes from execute_loads. ldr x3,[x2] picks up whatever follows ldvar as the high half of the value that gets added to the loop counter after each iteration. If this high half is non-zero then cmp x1,x4 never matches.  That's also why it doesn't reproduce consistently. If the compiler or linker places 0x00000000 next to ldvar then the test works as expected.

str x1,[x2] in execute_stores has a similar bug where 8 bytes are stored in the 4-byte stvar. Although this does not cause the hanging test.

Here's a reproducer:

```
cat > repro.c <<'EOF'
#include "testcode.h"
int main(void) { execute_stores(1000); execute_loads(1000); return 0; }
EOF

gcc -O2 repro.c src/validation_tests/load_store_testcode.c \
    -Isrc/validation_tests -o repro

timeout 5 ./repro; echo "exit=$?   # 124 means it hung"
```

exit=124 on master and on the #671 branch.

Here's a fix that worked for me. Intended to be applied on top of the #671 commit:

```diff
--- a/src/validation_tests/load_store_testcode.c
+++ b/src/validation_tests/load_store_testcode.c
@@ -6,10 +6,11 @@
 #if defined(__aarch64__)
 
 	__asm(  ".data\n"
-		"stvar: .word 1 /* stvar in memory */\n"
+		".balign 8\n"
+		"stvar: .xword 1 /* stvar in memory */\n"
 		".text\n"
 		"	ldr x2, =stvar /* address of stvar */\n"
-		"	mov x4, %0\n"
+		"	mov x4, %x0\n"
 		"	mov x1, #0\n"
 		"str_loop:\n"
 		"	str x1, [x2] /* store into stvar */\n"
@@ -18,7 +19,7 @@
 		"	bne str_loop\n"
 		:
 		: "r" (n)
-		: "cc" /* clobbered */
+		: "cc", "x1", "x2", "x4" /* clobbered */
 	);
 
 	return 0;
@@ -35,10 +36,11 @@
 #if defined(__aarch64__)
 
 	__asm(  ".data\n"
-		"ldvar: .word 1 /* ldvar in memory */\n"
+		".balign 8\n"
+		"ldvar: .xword 1 /* ldvar in memory */\n"
 		".text\n"
 		"	ldr x2, =ldvar /* address of ldvar */\n"
-		"	mov x4, %0\n"
+		"	mov x4, %x0\n"
 		"	mov x1, #0\n"
 		"ldr_loop:\n"
 		"	ldr x3, [x2] /* load from ldvar */\n"
@@ -47,7 +49,7 @@
 		"	bne ldr_loop\n"
 		:
 		: "r" (n)
-		: "cc" /* clobbered */
+		: "cc", "x1", "x2", "x3", "x4" /* clobbered */
 	);
 
 	return 0;
```

**Comment by dbarry9** [comment]
@aaronmerey Thank you for your reply. I will add your changes as a commit.

**Comment by dbarry9** [comment]
> After updating to commit [7710a20](https://github.com/icl-utk-edu/papi/commit/7710a20ed72bb984b52a1d575a2d707d548de35b) the validation tests papi_ld_ins hang indefinitely when run on an ARM Neoverse N1 system.
> 
> This occurs in the execute_loads and execute_stores assembly routines introduced by that commit. It appears that an infinite loop is caused by the loop counters that are part of the test not progressing as expected on Neoverse N1.
> 
> System: Architecture: ARMv8 (AArch64) Microarchitecture: Neoverse N1 OS: Fedora rawhide (Linux 6.16.0-0.rc5.16.fc43.aarch64)

@aaronmerey Just for the sake of documentation, could you please also provide the compiler, version, and any additional flags you use before you configure PAPI?

**Comment by dbarry9** [comment]
@aaronmerey I have updated PR #671 per your changes. Could you please test this branch and check that I implemented your changes properly?

**Comment by aaronmerey** [comment]
@dbarry9, The update to #671 fixes the bug for me. I didn't record which GCC version I originally reproduced this bug with. But for the latest round of testing I used `gcc (GCC) 16.1.1 20260515 (Red Hat 16.1.1-2)` on Fedora 44 kernel `7.1.6-201.fc44.aarch64`. I also used `CFLAGS='-Og -ggdb -D_GLIBCXX_DEBUG -D_GLIBCXX_DEBUG_PEDANTIC'`.
